config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  # devise_for :users

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  private

    def not_authenticated
      redirect_to login_path, alert: "Please login first"
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!, only: :show  
  def index
  end

  def show
    @users = User.order('updated_at DESC')
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: :destroy
  
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to :users, notice: 'Login successful'
    else
      flash.now[:alert] = 'Login failed'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]

  def index
    @users = User.order('updated_at DESC')
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to :users, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/home/index.html.slim
- if user_signed_in?
  p = link_to "Log Out", destroy_user_session_path, method: :delete

h1 Home#index
p Find me in app/views/home/index.html.slim

= link_to "See all users", users_path

app/views/home/show.html.slim
= link_to "Log Out", destroy_user_session_path, method: :delete

h1 Show all users

table
  thead
    tr
      th ID
      th Email
      th Encrypted password
      / th Salt

  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = user.email
        td = user.encrypted_password
        / td = user.salt

p = link_to "Home", root_path

app/views/layouts/application.html.slim
html
  head
    title DeviseToSorceryRenameEncryptedPasswordAttribute
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    #nav
      - if current_user
        = link_to "Edit Profile", edit_user_path(current_user.id)
        = link_to "Logout", :logout, method: :post
      - else
        = link_to "Register", new_user_path
        '  | 
        = link_to "Login", :login
    div
      p#notice = flash[:notice]
      p#alert = flash[:alert]

    = yield

app/views/user_sessions/_form.html.slim
= form_tag user_sessions_path, :method => :post do
  
  .field
    = label_tag :email
    = text_field_tag :email
  .field
    = label_tag :password
    = password_field_tag :password
  .actions
    = submit_tag "Login"

app/views/user_sessions/crete.html.slim
h1 UserSessions#crete
p Find me in app/views/user_sessions/crete.html.slim

app/views/user_sessions/destroy.html.slim
h1 UserSessions#destroy
p Find me in app/views/user_sessions/destroy.html.slim

app/views/user_sessions/new.html.slim
h1 Login

= render 'form'

= link_to 'Back', user_sessions_path

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :password_confirmation
    = f.text_field :password_confirmation
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
= link_to 'Log Out', destroy_user_session_path, method: :delete

h1 All users

table
  thead
    tr
      th ID
      th Email
      th Crypted password
      th Salt
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = user.email
        td = user.encrypted_password
        td = user.salt
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)

p = link_to 'Home', root_path
p = link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Email:
  = @user.email
p
  strong Crypted password:
  = @user.crypted_password
p
  strong Salt:
  = @user.salt

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path